### ISSUE TITLE
Cloudflare change again 

### ISSUE THREAD

**Issue by Arias800** [Arias800/CloudflareScraper#3]
Cloudflare change again there algorithm . Exemple here : http://japscan.to/
```
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\CloudflareScraper\__init__.py", line 213, in <genexpr>
    str(sum(int(digit_char) for digit_char in digit_expression[1:-1])) # Strip the parenthesis.
ValueError: invalid literal for int() with base 10: 'c'
```

**Comment by doko-desuka** [comment]
Thanks @Arias800, I'll take a look.

**Comment by doko-desuka** [comment]
I'm on my phone right now, but it should work if you change the 'eval(eval(atob' string pattern to 'eval(eval(' (on line 130)

**Comment by ebs111222** [comment]
@doko-desuka 
it works thank you
and you fixed it over the phone?? 
you are the king !! thanks

**Comment by bjgood** [comment]
How did you do that, doko? On your phone? Impressive. Way to go. :D. It works.

Thanks for your site, Arias800.

**Comment by doko-desuka** [comment]
On Chrome for Android you need to use "view-source:https\:\/\/blabla.com" as the address and it'll show you the page source code as text.  
The CF challenge code is (for the time being) still human readable.

**Comment by Arias800** [comment]
Fix here : https://github.com/Arias800/CloudflareScraper/commit/00d2241650aab589c7ce867c347f298a90a7fefd#diff-bdff67e3f5690fd54e38e2cf40d61f1e
Thanks @doko-desuka for your help ^^

**Comment by bjgood** [comment]
Much better, doko and Arias800. It works good as is. Pulls in a lot more results.

**Comment by doko-desuka** [comment]
Thanks for the patch @Arias800.
