### ISSUE TITLE
Not working for some sites...

### ISSUE THREAD

**Issue by ebs111222** [Arias800/CloudflareScraper#5]
hi 
your code is great, thanks alot.
can you please check why does not it works for some sites like:
https://www.digbt.org/
https://worldwidetorrents.to/
https://zooqle.me/
thanks alot.

**Comment by Arias800** [comment]
Hi,
All website work for me except the last one so try with the lastest version ^^

**Comment by Matthew17-21** [comment]
HI! I just updated it and doesn't seem to be working on 
https://footdistrict.com/en/ or https://www.nakedcph.com/
can anyone confirm if it's just me or you are experiencing the same thing. Thank you

**Comment by doko-desuka** [comment]
@mlugo2017 you should read what your site says:

> Due to the limited-edition sneaker we are currently releasing, we are experiencing not only an increased number of customers, but also an increased number of online bots. To prove that you are not a bot, we need you to complete a CAPTCHA.

It's always using the captcha mode, whose main purpose is to block bots.

**Comment by doko-desuka** [comment]
That was for the "nakedcph" domain. 

The "footdistrict" domain uses its own JS block, you'll have to make a solver for that.  
It looks straightforward enough, some  obfuscation.

**Comment by doko-desuka** [comment]
@ebs111222 that "zooqle" domain that isn't working (thanks to @Arias800 for testing the others with the solver) also always uses the captcha mode, unfortunately.
